### ISSUE TITLE
Make error.

### ISSUE THREAD

**Issue by wpoosanguansit** [dancingrobot84/purescript-express#10]
I ran grunt make and this is the error I am having:

Running "pscMake:0" (pscMake) task
>> Make failed:
>> Error at src/Node/Express/Internal/QueryString.purs line 11, column 1 - line 12, column 1: 
>> Error in module Node.Express.Internal.QueryString
>> Cannot import unknown module 'Control.Alternative'

Could you share abit how to run the code?  Thank you for your help.

**Comment by garyb** [comment]
Did you run `bower install` first?

**Comment by wpoosanguansit** [comment]
I see now that it didn't fully install the first time.  I now able to start example.js which is being poited to at port 3000.  Thanks for your help.

**Comment by garyb** [comment]
You're welcome :)
