### ISSUE TITLE
'getBodyParam' doesn't work...

### ISSUE THREAD

**Issue by bkyrlach** [dancingrobot84/purescript-express#11]
In the current version of 'express.js' it does not parse the request body by default. This means that the 'getBodyParam' method throws runtime exceptions. There's also no easy way that I can see in the current API to turn on the 'body-parser' library (should one have it installed).

I hacked a solution that works, but it's not clean enough to submit as a PR (it makes some assumptions, so it's not likely to work for everyone). If you have some ideas on a fix, I'd be happy to contribute.

**Comment by dancingrobot84** [comment]
Thanks! I guess I missed this behaviour of express.js. I'll take a look into it soon and try to find a way to fix this.

**Comment by dancingrobot84** [comment]
I've fixed runtime exceptions: check whether body is defined or not before getting anything from it and if it's undefined return nothing. Not sure if it's good to be silent when body is not parsed, but I'm going to rewrite a lot of internal functions later anyway, so I guess it's ok for now.

Also I've added [example](https://github.com/dancingrobot84/purescript-express/blob/master/examples/JSMiddleware.purs) showing how to attach JS middleware. I haven't used API for this myself, so if you see any pitfalls please tell me and I'll fix them.
