### ISSUE TITLE
Make it easy to embed an App in an existing JavaScript express application

### ISSUE THREAD

**Issue by dvdsgl** [dancingrobot84/purescript-express#12]
I have a large express app written in JavaScript, and I'd like to start writing new handlers in purescript. I'd like to be able to do this:

In `Main.purs`:

```purescript
module Main (initialize) where

app :: App
app = get "/ps" $ send "Hello, PureScript!"

initialize :: Fn1 Application Unit
initialize = Node.Express.App.embedded app
```

In `server.js`:

```javascript
var Main = require("Main");
var app = require("express")();

app.get("/js", function(req, res) { res.send("Hello, JavaScript!"); });
Main.initialize(app);
app.listen(8080);
```

I'm not sure if there's a better semantics for this, but it would really help existing express apps implement new functionality in purescript, and eventually port entirely, which is my goal.

**Comment by dancingrobot84** [comment]
Hi! Thanks for suggestion. I've added `apply` function that allows you to do this thing and [example](https://github.com/dancingrobot84/purescript-express/blob/master/examples/EmbedApp.purs) of its usage.

**Comment by chexxor** [comment]
The example you provided didn't answer a similar problem I wanted to solve: I want to maintain a `server.js` JavaScript file which has `var app = require('express')().use(...).get(...).listen(3000);`, but I also want to write a bunch of HTTP request handlers in PureScript. How, then, do we compile the PureScript and attach those handlers into this `app`?

After lots of poking and experimenting, I discovered it's possible by using the `apply` function. See these file snippets:

``` purescript
module App.Server.Database where
-- (imports elided)
getInventoryHandler :: forall e. Handler e
getInventoryHandler =
  do
    -- Demo that we have access to request data.
    p <- getPath
    b <- getBodyParam "test"
    m <- getMethod
    trace ("path:" <> p) \_ ->
    trace ("bodyParam:" <> (fromMaybe "no bodyParam" b)) \_ ->
    trace ("method:" <> (fromMaybe "no method" (show <$> m))) \_ ->
    -- Reply "Inventory" to any requests for "/inventory".
    send "Inventory"
inventoryEndpoints :: forall e. App e
inventoryEndpoints = do
  get "/inventory" getInventoryHandler
```

``` javascript
var express = require('express');
var app = express();

// Apply express app config written in PureScript to this express app.
var App_Server_Database = require('./output/App.Server.Database');
var Node_Express_App = require('./output/Node.Express.App');
Node_Express_App.apply(App_Server_Database.inventoryEndpoints)(app)()
// Separate config additions enable adding PS handlers anywhere in handler chain.
app = app.use(express.static('./static'));
// Order of request handling is important
//   - maybe we need to attach inventoryEndpoints after here instead.
app.listen(3000);
```
