### ISSUE TITLE
Example in adding new middlewares into the app.

### ISSUE THREAD

**Issue by wpoosanguansit** [dancingrobot84/purescript-express#13]
I just found this project.  And I am still trying to figure things out.  Would it be possible to add to the example how one can add new middlewares into the app?  Thanks for your help.

**Comment by dancingrobot84** [comment]
Hi! Thank you. I've added example for JS middleware [here](https://github.com/dancingrobot84/purescript-express/blob/master/examples/JSMiddleware.purs). If you want to write middleware in PS you can take a look at logger [implementation](https://github.com/dancingrobot84/purescript-express/blob/master/examples/ToDoServer.purs#L52) and [usage](https://github.com/dancingrobot84/purescript-express/blob/master/examples/ToDoServer.purs#L124) in Todo server example
