### ISSUE TITLE
Offer HandlerM built on Aff (Asynchronous Eff)

### ISSUE THREAD

**Issue by dvdsgl** [dancingrobot84/purescript-express#15]
It would be really cool if HandlerM were a transformer on Aff (https://github.com/slamdata/purescript-aff), or to offer AsyncHandlerM so we could more easily write Handlers with lots of callbacks:

```purescript
asyncHandler :: AsyncHandler
asyncHandler = do
  info <- liftAff $ JQuery.get "/info.json"
  users <- liftAff $ Database.query "SELECT * FROM USERS"
  sendJson { info: info, users: users }

app = do
  get "/foo" asyncHandler
```

Doing something like this with `capture` can get ugly.

**Comment by dancingrobot84** [comment]
Haven't heard of Aff, but it's definitely better than `capture`. Thanks!

**Comment by michaelficarra** [comment]
:+1:, I was just trying to use purescript-express with redis, and the node redis library is entirely asynchronous, so I have no way to write a handler that can respond based on my interaction with redis. :cry:

**Comment by kika** [comment]
How should I handle errors in Aff? I have a code like this: 
```Purescript
upstreamAuth (AppStateRecord state) token = do
  let opts = state.upstream 
           <> method := "POST"
           <> path := "/_session"
  reqdata <- liftEff $ Buffer.fromString token UTF8
  res     <- SR.simpleRequest opts reqdata
  pure res.body

checkAuth::forall e. AppState -> Token -> Aff (ref::REF, http::HTTP|e) Cookie
checkAuth stateref token = do
  state <- liftEff $ readRef stateref
  case getSession token state of
    Nothing      -> upstreamAuth state token
    Just session -> pure session.cookie

authHandler :: forall e.  AppState -> Handler (console::CONSOLE, http::HTTP, ref::REF | e)
authHandler statedata = do
  token <- getRequestHeader "Authorization"
  case token of
    Nothing   -> nextThrow $ error "NOAUTH"
    Just user -> case parseUser user of
      "" -> nextThrow $ error "NOAUTH"
      u  -> do
        liftEff $ log ("API token: " <> u)
        cookie <- liftAff $ checkAuth statedata u
        liftEff $ log ("Cookie: " <> cookie)
        next
```
And the errors which happen in `upstreamAuth` are propagated to runtime exceptions without any possibility to handle them. I suppose that's where I should use `runAff`, and put `next` and `nextThrow` as success and failure callbacks but it requires handlers which return `Eff`, not `HandlerM`, as `runAff` does. Obviously, I'm missing something. 
How do you handle errors with Aff "subrequests" from Handlers?

**Comment by Risto-Stevcev** [comment]
@kika you can use `attempt` from the Aff lib

**Comment by kika** [comment]
@Risto-Stevcev right, that's what I've started with, but then it introduces another `case ... of Left -> ... Right -> ...` and I'm trying to join the [Destry All Ifs](http://degoes.net/articles/destroy-all-ifs) sect :-)
