### ISSUE TITLE
To respond with views.

### ISSUE THREAD

**Issue by wpoosanguansit** [dancingrobot84/purescript-express#16]
I am not sure if this is the correct way to try to respond with views which in js is

 res.render('index', { title: 'Hey', message: 'Hello there!'});

If i understand correctly, we would have to create a function like intlRespWithView and expose it via the external App.purs something like render :: String -> Json -> Handler

Is that how it should be done?

**Comment by dancingrobot84** [comment]
Hi! Sorry for being late, I missed your issue somehow. Responding with views is not supported right now. `intlRespWithView` seems to be the right way providing current state of ps-express.

**Comment by owickstrom** [comment]
Didn't see this issue before I posted https://github.com/dancingrobot84/purescript-express/pull/31, but I think this is what you are talking about, right?

**Comment by wpoosanguansit** [comment]
yes

**Comment by dancingrobot84** [comment]
Fixed with #31
