### ISSUE TITLE
Update for purescript 0.7

### ISSUE THREAD

**Issue by stkb** [dancingrobot84/purescript-express#20]
Are you planning to update this library for purescript 0.7 compatibility?

**Comment by dancingrobot84** [comment]
Hi! Yes, I'm planning to update purescript-express to the latest versions of PS and libraries and do some refactoring, but I can't tell you concrete date. Maybe in a couple of weeks or so.

**Comment by stkb** [comment]
Would you take a PR on it? I made it a little project over the weekend so now have a working 0.7 version on my machine. Have changed as little as possible.

**Comment by dancingrobot84** [comment]
Yes, I guess I would.

**Comment by stkb** [comment]
Ok thanks, I've [submitted a PR](https://github.com/dancingrobot84/purescript-express/pull/21) for your perusal
