### ISSUE TITLE
Bower file probably out of date

### ISSUE THREAD

**Issue by kjameslubin** [dancingrobot84/purescript-express#29]
```  pulp dep install https://github.com/dancingrobot84/purescript-express.git; pulp build ```

gives the following error message:
``psc: It looks like you are trying to use a feature from a previous version of the compiler:
Array notation is no longer supported. Use Array _ instead of [_].`` 

I checked that the master branch bower file and the last version tagged bower file do not match, and bower seems to fallback to the last [tagged](http://stackoverflow.com/questions/29046960/bower-json-main-is-present-but-i-get-a-is-missing-main-entry-in-bower) bower file, which appears out of date. I'm a node-world newbie, but I think the only way around this is cloning and editing the bower file locally. Thanks.

**Comment by stkb** [comment]
Yeah bower's installing the last tagged version of purescript-express there (v0.2.0) and that is an outdated version, before changes were made to make it compatible with the new purescript 0.7 compiler.

Not sure when @dancingrobot84 is planning on doing a version bump, but the version in master is working fine, so you can tell bower to download from the master branch instead by adding `#master`, ie:

`pulp dep install https://github.com/dancingrobot84/purescript-express.git#master`

or just 

`pulp dep install purescript-express#master`

It should then build fine.

**Comment by kjameslubin** [comment]
That is what I ended up doing. I didn't know about the #master tag though, thanks
