### ISSUE TITLE
Let's make a similar wrapper for Koa server :)

### ISSUE THREAD

**Issue by kristianmandrup** [dancingrobot84/purescript-express#32]
Anyone interested?

**Comment by jgoux** [comment]
I'm really interested by this ! :+1:

**Comment by kristianmandrup** [comment]
Then let's do it!! I will start a repo ;) I have some exp with Koa and porting for other frameworks, but very little purescript experience.

**Comment by akilegaspi** [comment]
Was this ever realized? I'm interested in chipping in
