### ISSUE TITLE
ToDoServer enhancement suggestion

### ISSUE THREAD

**Issue by kika** [dancingrobot84/purescript-express#35]
ToDoServer enhancement suggestion:
https://github.com/kika/purescript-express-todoserver

Basically the same thing, but I hope in a more Purescript idiomatic way, without so many foreign imports.
I can make it as a PR or just grab it from there if you like.

**Comment by dancingrobot84** [comment]
@kika Thanks! I'll take a look at it this weekend.

**Comment by dancingrobot84** [comment]
Replaced todo server example with yours. Thank you again :+1:
