### ISSUE TITLE
Add to Pursuit

### ISSUE THREAD

**Issue by Zenleaf** [dancingrobot84/purescript-express#41]
Hi this is an awesome initiative to use Purescript on the server side as well. I didn't find this library on Pursuit. Why not add it there?

**Comment by dancingrobot84** [comment]
Hi @Zenleaf! It's strange, because I've added ps-express there some time ago. Nevertheless, I can do it again.

**Comment by dancingrobot84** [comment]
Uploaded docs: https://pursuit.purescript.org/packages/purescript-express/0.3.3
