### ISSUE TITLE
All tests pass with purescript-aff 0.16.1

### ISSUE THREAD

**Issue by jedahu** [dancingrobot84/purescript-express#42]
I have a project that chokes on `bower install` because it requires both purescript-aff 0.13.0 (via purescript-express) and 0.16.1 (via another dependency).

Adding `"purescript-aff": "^0.16.1"` to bower resolutions has not fixed the issue.

All tests pass with 0.16.1. Do you mind updating?

**Comment by dancingrobot84** [comment]
Hi @jedahu,
Nope, I don't mind. Dependencies are updated in purescript-express 0.3.3.

**Comment by jedahu** [comment]
Thanks @dancingrobot84.
