### ISSUE TITLE
Alter request

### ISSUE THREAD

**Issue by kika** [dancingrobot84/purescript-express#46]
As I understand current best Express practice, the idiomatic way of passing data between middlewares is to assign to the Request object like `req.someData = {whatever: "foobar"}`
Is there no way to do that in Purescript implementation, or I'm just blind?

**Comment by dancingrobot84** [comment]
@kika I think you're right. `Request` is just opaque datatype in ps-express for now. Probably it is a good idea to make a couple of combinators for putting/getting data to/from request object.

**Comment by kika** [comment]
Okay, I'll do a PR as soon as I figure out how to handle errors from Aff "subrequests"
( https://github.com/dancingrobot84/purescript-express/issues/15 )
If you have an idea what to do there, I'd appreciate an advice.

How does such Request API look like:
```Purescript
setUserData::forall a e. String -> a -> Handler e
getUserData::forall a e. String -> HandlerM (express::EXPRESS|e) (Maybe a) 
```
