### ISSUE TITLE
How can I serve static files?

### ISSUE THREAD

**Issue by perglr** [dancingrobot84/purescript-express#50]
This is probably not implemented, yet. Can you please advise me on a simple hack?

**Comment by dancingrobot84** [comment]
Hi! You can use either [sendFile](https://github.com/dancingrobot84/purescript-express/blob/master/docs/Node/Express/Response.md#sendfile) or [sendFileExt](https://github.com/dancingrobot84/purescript-express/blob/master/docs/Node/Express/Response.md#sendfileext). They will call expressjs' [sendFile](http://expressjs.com/en/4x/api.html#res.sendFile) under the hood.

**Comment by perglr** [comment]
Thx!

**Comment by chexxor** [comment]
@dancingrobot84 Express 4 ships with [serve-static](https://github.com/expressjs/serve-static), located at [`express.static`](http://expressjs.com/en/starter/static-files.html). I'd like to make a PR to include an FFI to this - what do you think?

**Comment by dancingrobot84** [comment]
@chexxor That would be good :)
