### ISSUE TITLE
Support the static handler.

### ISSUE THREAD

**Issue by raduom** [dancingrobot84/purescript-express#57]
I needed static support for an app I am working on, and I wrote something up that works for me.
Would you be interested in a pull request with the code?

**Comment by chexxor** [comment]
Yeah, it would be welcome: https://github.com/dancingrobot84/purescript-express/issues/50

**Comment by raduom** [comment]
I also wrote a wrapper around cookie-parser in order to be able to get the cookies set on the request. Would that be also something you would consider merging? Should I put up a new issue?

**Comment by dancingrobot84** [comment]
@raduom Yes, please :) If you have a code for it, you can send a PR straightaway.
